### ISSUE TITLE
Evil-escape causes key repetition

### ISSUE THREAD

**Issue by AlexLewandowski** [shg/julia-vterm.el#7]
With an evil escape sequence like "jk", julia-vterm will repeat (and overwrite) keys if entered quickly. 

For example, typing "je" quickly will result in a "jj". Similarly, "ks" will result in "kk". Basically, the second character will be replaced with the first character if the first character is part of an evil-escape sequence. This doesn't happen in vterm and not sure how to debug. 

I have moved away from evil-escape sequences and use ctrl-g for escape in doom-emacs now, which does not pose an issue.

**Comment by shg** [comment]
Thank you for reporting the issue. I do not use evil-mode regularly but as far as I checked very quickly I couldn't see the phenomenon that you reported in my environment. Do you see the same issue with a shell running in vterm as well or only in julia-vterm?

**Comment by AlexLewandowski** [comment]
It seems like a known issue with vterm/evil-escape (https://github.com/akermu/emacs-libvterm/issues/247). But the strange thing is, it only occurs in julia-vterm for me (not regular vterm).

**Comment by shg** [comment]
Thank you for the link. Since it seems primarily evil-escape's issue, I guess doing something in julia-vterm now is probably not a good idea. So let me close this for now. Please reopen it if you find anything about why the issue exists only in julia-vterm in your environment.

It seems the issue has been around for 2 years.

https://github.com/syl20bnr/evil-escape/pull/87
